### ISSUE TITLE
The death of the eldest (quest)

### ISSUE THREAD

**Issue by Sucoman** [LegionIsrael/LegionIsraelBugTracker#11]
שם השחקן
psyco
תיאור הבעיה
אי אפשר לסיים את המשימה
איך אפשר לגרום לזה להראות את הבאג המתואר במשחק
יש חלק במשימה שצריך לזרוק משהו שאספת לתוך אגם, ואי אפשר לזרוק אותו.
איך זה אמור לעבוד?
לא זוכרב לדעתי לוחצים על החפץ וזה נזרק לאגם כשאתה מספיק קרוב אליו
השם של המפלצת, או של האובייקט, או של האייטם, עדיף גם entry מwowhead אם אפשר

רמת דחיפות: נמוך, בינוני, גבוה, קריטי
תלוי בכם, זה ו
קווסט שאי אפשר להמשיך בלעדיו.

**Comment by LegionIsrael** [comment]
תוקן
