### ISSUE TITLE
Cant use taxi while [Mounted-Shapeshifted]

### ISSUE THREAD

**Issue by shalevb13** [LegionIsrael/LegionIsraelBugTracker#14]
When you are mounted or shapeshifted u cant use Taxi [Flight] and instead of just getting u off mount or getting you out for shapeshift auto and take you, you need to do it your self and its kind of useless and not how it should be.

**Comment by LegionIsrael** [comment]
צריך לזה פתרון אוטומטי? אי אפשר פשוט לחזור למצב רגיל לפני כן?
