### ISSUE TITLE
Graveyard Valshara

### ISSUE THREAD

**Issue by shalevb13** [LegionIsrael/LegionIsraelBugTracker#15]
הייתי ב וורלד קווסט [DANGER: Kathaw the Savage]
 ב grave yardומתתי וכשלחצתי לחזור לחיים זה פשוט שיגר אותי ל Kalimdor-The crossroads, Northern Barrens

**Comment by LegionIsrael** [comment]
לא קריטי כרגע, נדחה לאחר כך

**Comment by Sucoman** [comment]
ממש לאת כל פעם שמתים בברוקן איילז, חוזרים איפהשהוא. אני עולה רמות ואני מת ממובים וכל פעם אני צריך לחזור ליד אורגימר ולשרוד את ה10 דקות של הסיקנס. זה ממש לא בעדיפות נמוכה

**Comment by shalevb13** [comment]
מסכים כדאי שזה יהיה בעדיפות גבוהה

**Comment by shalevb13** [comment]
פירסמתם בתיקונים שתיקנתם את זה אבל במקום שזה יקח אותך לאורגימר מת זה מחזיר אותך חיי

**Comment by shalevb13** [comment]
אז עדיין יש שיפור אבל זה לא פותר את הבעיה

**Comment by LegionIsrael** [comment]
אוקיי טעות שלנו, תיקון הבא זה יסתדר
