### ISSUE TITLE
Fel Rush

### ISSUE THREAD

**Issue by Sucoman** [LegionIsrael/LegionIsraelBugTracker#16]
שם השחקן
Psyco
תיאור הבעיה
המתקפה (Fel Rush) 
אמורה לעשות דאש למרחק מסויים, כשאני עושה אותה על הקרקע, זה זז לי כמו שזה אמור. כשאני עושה אותה באוויר היא עוברת בערך רבע מהמרחק שצריך

אין לי עוד מה לרשוםת כי זה תיאור מתקפה וזה מתיקף הכלת אולי את הרמת דחיפות קריטית, זה מקשה מאוד לשחק עם הדמות.

**Comment by LegionIsrael** [comment]
ניסיתי תיקון, עוד מעט אבדוק לוקאלית ואעדכן
