### ISSUE TITLE
[Quest]Butcherbot

### ISSUE THREAD

**Issue by ghost** [LegionIsrael/LegionIsraelBugTracker#2]
Quest : Use the Butcherbot to harvest 10 Glasshide Basilisk corpses.
Nothing happen after you use the item
You are not harvesting the corpse

Link : https://www.wowhead.com/quest=25112/butcherbot
Item : https://www.wowhead.com/item=52715/butcherbot-control-gizmo

**Comment by LegionIsrael** [comment]
i just attempted a fix, will come back later with the results
