### ISSUE TITLE
quest  [By Any Means]

### ISSUE THREAD

**Issue by Sucoman** [LegionIsrael/LegionIsraelBugTracker#21]
שם השחקן
Psyco
תיאור הבעיה
הקווסט לא מצליח לשנות את המטרה של הדאנג'ן
איך אפשר לגרום לזה להראות את הבאג המתואר במשחק
בקווסטים של הדימון האנטר צריך להיכנס לדאנג'ן שבתוך דאלארןת אבל כשאתה מנסה להיכנס זה מנסה להיכנס לדאנג'ן רגיל ולא לסנריו שאתה אמור להיכנס אליו

איך זה אמור לעבוד?
אני אמור להיכנס לסנריו כזה

השם של המפלצת, או של האובייקט, או של האייטם, עדיף גם entry מwowhead אם אפשר

תוקע קווסטים של DH, אז די דחוף

**Comment by LegionIsrael** [comment]
אני לא בטוח שאני מבין, באיזה חלק אתה מדבר כי הקמפיין של הDH ארוך מאוד
באיזה שלב זה יהיה מ ושלם אצלנו אבל כרגע עשינו חצי והשאר לוקחים פורטל שנותן לך את מה שאתה צריך 

כרגע זה יורד לפירויטי נמוך מאוד, צר ל

**Comment by LegionIsrael** [comment]
תנסה להסביר איפה זה בקמפיין אם זה אחרי שעה שעתיים ופתאום אין פיתוח בהמשך זה ידוע מרא. רק אומר אבל שוב תלוי באיזה שלב.
אתה אמור לקבל פורטל לעיר שלך כשכביכול הפיתוח נגמר שם הבנת?
