### ISSUE TITLE
אי Gloaming reef

### ISSUE THREAD

**Issue by Sucoman** [LegionIsrael/LegionIsraelBugTracker#23]
שם השחקן
Psyco
תיאור הבעיה
מתתי באי Gloaming Reef שנמצא בצד  שמאל של Val'sharah והרוח של הדמות שלי הופיע ליד orgrimmar
איך אפשר לגרום לזה להראות את הבאג המתואר במשחק
תמותו באית ואיכשהוא הרוח שלכם תשתגר לליד אורגימר ועכשיו צריכים לעבור לשם
איך זה אמור לעבוד?
אני אמור להשתגר לגרייביארד הקרוב
השם של המפלצת, או של האובייקט, או של האייטם, עדיף גם entry מwowhead אם אפשר
אין
רמת דחיפות: נמוך, בינוני, גבוה, קריטי
קריטית הדמות שלי תקועה ולא יכולה לעשות כלום

**Comment by LegionIsrael** [comment]
מסדרים תיקון כללי לבעיה הזאת בברוקן איילס, אז אני מחשיב את זה ועוד אחרים כמתוקן
