### ISSUE TITLE
אין שיתוף של מאונטים

### ISSUE THREAD

**Issue by Sucoman** [LegionIsrael/LegionIsraelBugTracker#25]
שם השחקן
Psyco
תיאור הבעיה
 אין שיתוף בין המאונטים  בכל הדמויות
איך אפשר לגרום לזה להראות את הבאג המתואר במשחק
מאונט שאני מקבל בדמות אחת לא מופיע לי בשניה
איך זה אמור לעבוד?
מאונטים זה דבר שמשותף בכל המשתמש
השם של המפלצת, או של האובייקט, או של האייטם, עדיף גם entry מwowhead אם אפשר
כל מאונט אפשרי
רמת דחיפות: נמוך, בינוני, גבוה, קריטי
גבוהה, זה הורס קצת את המשחק לקנות מאונטים בכל דמות

**Comment by LegionIsrael** [comment]
יטופל בהמשך
