### ISSUE TITLE
Slugmaw לא ניתן להריגה על ידי melee users

### ISSUE THREAD

**Issue by Daniel83Y** [LegionIsrael/LegionIsraelBugTracker#26]
![image](https://user-images.githubusercontent.com/43648186/46174979-1b6f1780-c2b3-11e8-96a2-f0b69a685545.png)

**Comment by LegionIsrael** [comment]
מה לעזאזל הריפורט הזה?

**Comment by Daniel83Y** [comment]
אי אפשר להרוג אותו
אבל אני לא מצליח למצוא אותו בwow head

**Comment by Daniel83Y** [comment]
Slagmaw

**Comment by Daniel83Y** [comment]
https://www.wowhead.com/npc=61463/slagmaw

**Comment by LegionIsrael** [comment]
אוקיי אברר את זה עכשיו, תודה על ההסבר

**Comment by LegionIsrael** [comment]
עדכון: תוקן
