### ISSUE TITLE
Ogunaro wolf trainer אי אפשר לדבר איתו והוא המוכר של חיות הרכיבה

### ISSUE THREAD

**Issue by Daniel83Y** [LegionIsrael/LegionIsraelBugTracker#28]
![image](https://user-images.githubusercontent.com/43648186/46175778-c84a9400-c2b5-11e8-8fd0-cd06f8d58496.png)
Ogunaro wolf trainer אי אפשר לדבר איתו והוא המוכר של חיות הרכיבה
Vallley Of Honor

**Comment by LegionIsrael** [comment]
אפשר לינק מואו האד?

**Comment by Daniel83Y** [comment]
https://www.wowhead.com/npc=3362/ogunaro-wolfrunner

**Comment by LegionIsrael** [comment]
תוקן, היה חסר פלאג של מוכר
