### ISSUE TITLE
Priest Class Hall

### ISSUE THREAD

**Issue by Sucoman** [LegionIsrael/LegionIsraelBugTracker#29]
היי,  אי אפשר להכנס לקלאס הול של הפריסט. הגעתי לפורטל ופשוט לא יכולתי ללחוץ על כלום.

**Comment by LegionIsrael** [comment]
איך אתה בודק את זה בדיוק, אני עם אליינס וזה עובד... עובד ממש טוב


![capture2](https://user-images.githubusercontent.com/43454471/46211568-89abec80-c33c-11e8-84d9-d61e93e848d6.JPG)
![capture](https://user-images.githubusercontent.com/43454471/46211569-89abec80-c33c-11e8-82d8-ec4550b3ff75.JPG)
![capture1](https://user-images.githubusercontent.com/43454471/46211570-89abec80-c33c-11e8-8d67-a41c1bd389dc.JPG)

**Comment by Sucoman** [comment]
עם אלייאנס כנראה זה עובד, בהורד זה לא עובד

**Comment by LegionIsrael** [comment]
תוקן
