### ISSUE TITLE
[Quest]Scavengers Scavenged

### ISSUE THREAD

**Issue by ghost** [LegionIsrael/LegionIsraelBugTracker#3]
Quest : Use Butcherbot to harvest 12 Fire Roc corpses
After the item is used , there is animation of the action 
But there is no credit for the quest

https://www.wowhead.com/quest=25111/scavengers-scavenged
https://www.wowhead.com/item=52715/butcherbot-control-gizmo

**Comment by LegionIsrael** [comment]
made an attempt to fix this with the other quest, confirmation will come quick
