### ISSUE TITLE
תקלה לגבי donate hierlooms set 

### ISSUE THREAD

**Issue by Daniel83Y** [LegionIsrael/LegionIsraelBugTracker#30]
מי שקונה hierlooms set 
neck ו Trinket 2מקבל הכל חוץ מ
והSHIFT P 
לא עובד לא מתחלק בין כל השחקנים לא בhierlooms ולא בmounts

**Comment by LegionIsrael** [comment]
מאונטים לא אקונט באונד, נכון

 ושהטרינקטים לא שם בכוונה, הפאק כולל רק חלק מהבגדי לבוש את כולם
