### ISSUE TITLE
Black Rook Hold Arena

### ISSUE THREAD

**Issue by shalevb13** [LegionIsrael/LegionIsraelBugTracker#34]
When u get in this arena u can click on the gates and open them before the arena even started.
you can also open the gates go outside and even go to the enemy team side and when it starts attack them from behinde.

**Comment by LegionIsrael** [comment]
עוד פרטים בבקשה זה לא עובד ככה חבר, אתה צריך להוסיף לינקים מואו האד לכל דבר שאתה מסביר עליו. אני לא יכול להתחיל לחקור בזה.

**Comment by shalevb13** [comment]
איזה עוד פרטים אני אמור לתת

**Comment by shalevb13** [comment]
אין ממש לינק בואו האד לgate
פשוט מאוד אתה נכנס לarena הזאת
יש שערים שחוסמים אותך בהתחלה מלצאת לרחבה ואפשר ללחוץ עליהם ולפתוח אותם סתם ככה ולצאת

**Comment by shalevb13** [comment]
אין עוד פרטים לכתוב על זה

**Comment by LegionIsrael** [comment]
Fixed

**Comment by LegionIsrael** [comment]
also applied to the other legion's dungeons. fixed also
