### ISSUE TITLE
WQ-Heads of the fleet

### ISSUE THREAD

**Issue by shalevb13** [LegionIsrael/LegionIsraelBugTracker#6]
לא ניתן לעשות כלום בקווסט

**Comment by LegionIsrael** [comment]
אחי תודה רבה על הרפורטים באמת זה עוזר רק אם אני יכול להעיר, יש מצב אם תוכל רק להוסיף עוד נתונים זה יהיה ממש נחמד

תודה שוב על העזרה, אעד עכשיו כל הרפורטים רלוונטים!!

**Comment by LegionIsrael** [comment]
המפלצות היו נטרליות

תוקן

**Comment by shalevb13** [comment]
כרגע הקווסט עלה שוב ועדיין המפלצות נטרליות
ואין אפשרות להשלים את הקווסט

**Comment by shalevb13** [comment]
כרגע הקווסט על שוב כל המפלצות בסדר חוץ מאחד שהוא עדיין נטרלי ואיאפשר להרוג ולסיים את הקווסט
[Second Mate cilieth slain]
