### ISSUE TITLE
 investigation at Mak'rana-WQ

### ISSUE THREAD

**Issue by shalevb13** [LegionIsrael/LegionIsraelBugTracker#7]
לא ניתן לעשות כלום ואין mobs באיזור

**Comment by LegionIsrael** [comment]
אחלה, נוספו 5 סוגי NPC:

MAKARA WARRIOR
MAKARA ELDER
BITTERSTONE VENOM
BITTERSTONE SNATCHER
OULIBION

תוקן

**Comment by shalevb13** [comment]
oulbion לא תקין 
ו Queen reprisal sailor "released'
לא עובד גם. 
כל השאר בסדר
